-- 002_insert_sample_users_data.sql
INSERT INTO users (name, email, role) VALUES
('Andi Prasetyo', 'andi.prasetyo@example.com', 'borrower'),
('Budi Santoso', 'budi.santoso@example.com', 'borrower'),
('Citra Dewi', 'citra.dewi@example.com', 'borrower'),
('Dewi Lestari', 'dewi.lestari@example.com', 'staff'),
('Eko Supriyanto', 'eko.supriyanto@example.com', 'staff'),
('Fani Mardiana', 'fani.mardiana@example.com', 'investor'),
('Gilang Mahardika', 'gilang.mahardika@example.com', 'investor'),
('Hanafi Hidayat', 'hanafi.hidayat@example.com', 'borrower'),
('Ika Nurhayati', 'ika.nurhayati@example.com', 'investor'),
('Joko Sumarno', 'joko.sumarno@example.com', 'staff'),
('Kiki Rahmawati', 'kiki.rahmawati@example.com', 'borrower'),
('Lina Sari', 'lina.sari@example.com', 'borrower'),
('Mikael Kristanto', 'mikael.kristanto@example.com', 'investor'),
('Nina Astuti', 'nina.astuti@example.com', 'investor'),
('Oka Prabowo', 'oka.prabowo@example.com', 'staff'),
('Pandu Setiawan', 'pandu.setiawan@example.com', 'borrower'),
('Qory Naufal', 'qory.naufal@example.com', 'borrower'),
('Rina Marisa', 'rina.marisa@example.com', 'staff'),
('Sandi Yudha', 'sandi.yudha@example.com', 'investor'),
('Tia Anggraeni', 'tia.anggraeni@example.com', 'borrower'),
('Umar Hamdani', 'umar.hamdani@example.com', 'investor'),
('Vina Maulani', 'vina.maulani@example.com', 'borrower'),
('Wahyu Setiawan', 'wahyu.setiawan@example.com', 'staff'),
('Xena Lestari', 'xena.lestari@example.com', 'borrower'),
('Yusuf Irfan', 'yusuf.irfan@example.com', 'investor'),
('Zahra Aisyah', 'zahra.aisyah@example.com', 'borrower');
